SRC_PATH=$(shell pwd)
CC=g++
CFLAGS=   
LIBS= 
#-lcurlpp -I./curlpp/include/
extlib = 
CXXFILE= phplikeCppCurl.cc
SO = phplikeCppCurl

include ../../../conf/Makefile_so.global
all:
	sudo cp phplikeCppCurl.so /usr/local/lib/node/libphplikeCppCurl.so

