.PHONY: basic curl exec md5 xml socket

gyp: basic curl exec md5 socket 
#xml

basic:
	cd basic/src && make gyp-ins

curl:
	cd curl/src && make gyp-ins

exec:
	cd exec/src && make gyp-ins

md5:
	cd md5/src && make gyp-ins

xml:
	cd xml/src && make gyp-ins

socket:
	cd socket/src && make gyp-ins
