.PHONY: basic curl exec md5 xml socket

all: basic curl exec md5 socket 
#xml

basic:
	cd basic/src && make

curl:
	cd curl/src && make

exec:
	cd exec/src && make

md5:
	cd md5/src && make

xml:
	cd xml/src && make 

socket:
	cd socket/src && make
