SRC_PATH=$(shell pwd)
CC=g++
CFLAGS=   
#LIBS= -lgd
extlib = 
CXXFILE= exec.cc
SO = exec
#include /usr/local/devlib/Makefile_exe_nodejs.global
include /home/program/lib/Makefile_so.global
all:
	sudo cp  exec.so /usr/local/lib/node/libexec.so

